In [1]:
# Solving 4x4 eigen value matrix problem of "S^2" operator for two non-interacting particle

In [2]:
import numpy as np
import scipy as sc
import scipy.linalg as sal

In [3]:
m = np.array([[2,0,0,0], [0,1,1,0], [0,1,1,0], [0,0,0,2]])
m

array([[2, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 2]])

In [4]:
val, vec = sal.eig(m)

In [5]:
vec, val

(array([[ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.70710678,  0.70710678,  0.        ,  0.        ],
        [ 0.70710678, -0.70710678,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([2.+0.j, 0.+0.j, 2.+0.j, 2.+0.j]))

In [9]:
m2 = np.array([[1,0,0,0], [0,-1,0,0],[0,0,1,0],[0,0,0,-1]])

In [10]:
val2, vec2 = sal.eig(m2)

In [11]:
val2, vec2

(array([ 1.+0.j, -1.+0.j,  1.+0.j, -1.+0.j]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))